default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: 127.0.0.1
  username: postgres
  password: postgres

development:
  <<: *default
  database: touchrails_development

test:
  <<: *default
  database: touchrails_test

production:
  <<: *default
  database: touchrails_production
  username: touchrails
  password: <%= ENV["TOUCHRAILS_DATABASE_PASSWORD"] %>
